micronaut:
  application:
    name: example-jpa
jackson:
  bean-introspection-module: true
---
datasources:
  default:
    url: jdbc:mariadb://localhost:3306/pets
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: secret
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
