micronaut:
  application:
    name: example-jpa
jackson:
  bean-introspection-module: true
---
datasources:
  default:
    url: jdbc:sqlserver://localhost:1433;databaseName=tempdb
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 'My!Secret123'
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
