micronaut:
  application:
    name: example-jpa
jackson:
  bean-introspection-module: true
---
datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/pets'
    driverClassName: org.postgresql.Driver
    username: postgres
    password: secret
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
